### ISSUE TITLE
Adopt upcoming Swift Evolution metadata file changes

### ISSUE THREAD

**Issue by dempseyatgithub** [attaswift/alfred-swift-evolution#2]
Hi, I'm James Dempsey, a member of the [Swift Website Workgroup](https://www.swift.org/website-workgroup/).

As part of the workgroup one area I’ve been focused on is the Swift Evolution Dashboard and the JSON file of evolution proposal metadata available at `https://download.swift.org/swift-evolution/proposals.json`.

I’m filing this issue because a GitHub search shows that this project references that URL.

I wanted to let you know that we are in the process of making some proposed changes to the schema and naming of the metadata file.

The proposed modifications are in the Swift Forums post at https://forums.swift.org/t/swift-evolution-metadata-proposed-changes/70779.

Please feel free to provide any feedback in that thread.

That post also describes the transition plan to migrate to the new metadata schema.

During the transition period, the `proposal.json` file will continue to be available at its current URL with its current schema.

A file with the new schema will also be available during the transition period.

For full details and to provide any feedback you may have, please review [the post in the Swift forums](https://forums.swift.org/t/swift-evolution-metadata-proposed-changes/70779).

**Comment by ole** [comment]
@dempseyatgithub Thanks a lot for the heads-up, James, that's very kind!

I plan to update the Alfred workflow to be compatible with the new format in a timely manner once the transition period starts.

**Comment by dempseyatgithub** [comment]
You're very welcome @ole. There's no need to break things unnecessarily, so it seemed like the best approach.

I saw your feedback in the forums. I'm out and about at the moment, but will reply later.

**Comment by dempseyatgithub** [comment]
An update that review period for the updated Swift Evolution metadata schema has ended.

The transition period to migrate to the new metadata schema and file has begun and will run through July 22, 2024.

Full details of the transition are available here:
https://forums.swift.org/t/swift-evolution-metadata-transition/71387

**Comment by ole** [comment]
This is now in progress: #4

**Comment by ole** [comment]
This is now live in [v2.2.0](https://github.com/attaswift/alfred-swift-evolution/releases/tag/v2.2.0).
